/// TODO: make new flutter fire project to make this file automatically
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJvjqkBMmLfJwCSuKTRtuP-Us_hCGzgDo',
    appId: '1:573002084717:web:1589cd59098b6d0b9dea64',
    messagingSenderId: '573002084717',
    projectId: 'example-fffe8',
    authDomain: 'example-fffe8.firebaseapp.com',
    storageBucket: 'example-fffe8.appspot.com',
    measurementId: 'G-Y7VQK368S6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTwwz78AvNGstuBMFwrWcyIMeDuHVg7U',
    appId: '1:573002084717:android:9fcbad4270431e229dea64',
    messagingSenderId: '573002084717',
    projectId: 'example-fffe8',
    storageBucket: 'example-fffe8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdt1-OcQqSTu2xMNKhgSoc5HLOBwbwG-w',
    appId: '1:573002084717:ios:de2d66952692b35d9dea64',
    messagingSenderId: '573002084717',
    projectId: 'example-fffe8',
    storageBucket: 'example-fffe8.appspot.com',
    iosClientId:
        '573002084717-6eqp284vm4hs1r3iln4k6q5ij6r7n1pn.apps.googleusercontent.com',
    iosBundleId: 'com.engmouaz.firebaseExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdt1-OcQqSTu2xMNKhgSoc5HLOBwbwG-w',
    appId: '1:573002084717:ios:de2d66952692b35d9dea64',
    messagingSenderId: '573002084717',
    projectId: 'example-fffe8',
    storageBucket: 'example-fffe8.appspot.com',
    iosClientId:
        '573002084717-6eqp284vm4hs1r3iln4k6q5ij6r7n1pn.apps.googleusercontent.com',
    iosBundleId: 'com.engmouaz.firebaseExample',
  );
}
